name: Style check
on: [push, pull_request]

jobs:
  lint:
      runs-on: [ubuntu-latest]
      steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25
      
      - name: Install libx11-dev for clipboard support
        if: runner.os == 'Linux'
        run: sudo apt install libx11-dev

      - name: Run go vet
        run: go vet ./...

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Check formatting with gofmt and goimports
        run: |
          gofmt -l .
          goimports -l .

      - name: Install revive
        run: go install github.com/mgechev/revive@latest

      - name: Run revive
        run: revive ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...